// SPDX-License-Identifier: Apache-2.0

//! Locates the `zkde_screencast_unstable_v1` protocol description and emits a
//! module that turns it into client bindings.
//!
//! The XML is **not vendored**. It is LGPL-2.1-or-later and this project is
//! Apache-2.0, so the file is read from the system copy shipped by
//! `plasma-wayland-protocols` instead of being copied into the tree.
//!
//! `wayland-scanner`'s macros take a path *literal*, which a discovered path
//! cannot be. So this writes a small wrapper module into `OUT_DIR` with the
//! resolved absolute path baked in, and `src/plasma/mod.rs` includes it.
//!
//! Nothing here runs unless the `plasma` feature is on, which keeps Hyprland
//! builds free of any KDE build dependency.

use std::path::{Path, PathBuf};

const XML_NAME: &str = "zkde-screencast-unstable-v1.xml";
const ENV_OVERRIDE: &str = "MORELAND_ZKDE_SCREENCAST_XML";

fn main() {
    println!("cargo:rerun-if-env-changed={ENV_OVERRIDE}");

    if std::env::var_os("CARGO_FEATURE_PLASMA").is_none() {
        return;
    }

    let xml = match locate_xml() {
        Some(path) => path,
        None => {
            // A hard error rather than a silent no-op: the feature was asked
            // for explicitly, so failing to honour it is a build failure.
            println!("cargo:warning=cannot find {XML_NAME}");
            panic!(
                "the `plasma` feature needs {XML_NAME}, which ships in \
                 plasma-wayland-protocols.\n\
                 Install it (Arch: `pacman -S plasma-wayland-protocols`), or \
                 point {ENV_OVERRIDE} at the file."
            );
        }
    };
    println!("cargo:rerun-if-changed={}", xml.display());

    let literal = xml.display().to_string();
    // The scanner emits `use` paths that assume these are in scope.
    let module = format!(
        r#"// @generated by build.rs — do not edit.
pub mod zkde_screencast {{
    use wayland_client;
    use wayland_client::protocol::*;

    pub mod __interfaces {{
        use wayland_client::protocol::__interfaces::*;
        wayland_scanner::generate_interfaces!({literal:?});
    }}
    use self::__interfaces::*;

    wayland_scanner::generate_client_code!({literal:?});
}}
"#
    );

    let out = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR")).join("plasma_protocol.rs");
    std::fs::write(&out, module).expect("writing generated protocol module");
}

/// Search the override, then every XDG data directory, then the usual prefixes.
fn locate_xml() -> Option<PathBuf> {
    if let Some(path) = std::env::var_os(ENV_OVERRIDE) {
        let path = PathBuf::from(path);
        return path.is_file().then_some(path);
    }

    let mut roots: Vec<PathBuf> = Vec::new();
    if let Ok(dirs) = std::env::var("XDG_DATA_DIRS") {
        roots.extend(dirs.split(':').filter(|s| !s.is_empty()).map(PathBuf::from));
    }
    roots.extend(
        ["/usr/share", "/usr/local/share", "/run/current-system/sw/share"]
            .iter()
            .map(PathBuf::from),
    );

    roots
        .into_iter()
        .map(|root| root.join("plasma-wayland-protocols").join(XML_NAME))
        .find(|candidate| Path::is_file(candidate))
}
